language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t chintandocker/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true chintandocker/docker-react npm run test